version: '3.7'

volumes:
  verdaccio:

services:
  app:
    image: verdaccio/verdaccio:4.x-next
    ports:
      - 4873:4873
    volumes:
      - verdaccio:/verdaccio/storage
      - ./config.yml:/verdaccio/conf/config.yaml
      - ./htpasswd:/verdaccio/conf/htpasswd